/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq;


import dev.abarmin.bots.entity.jooq.tables.ArticleSources;
import dev.abarmin.bots.entity.jooq.tables.ArticleSubscriptions;
import dev.abarmin.bots.entity.jooq.tables.Articles;
import dev.abarmin.bots.entity.jooq.tables.Episodes;
import dev.abarmin.bots.entity.jooq.tables.EpisodesArticles;
import dev.abarmin.bots.entity.jooq.tables.TelegramChats;
import dev.abarmin.bots.entity.jooq.tables.TelegramUpdates;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ARTICLE_SOURCES</code>.
     */
    public final ArticleSources ARTICLE_SOURCES = ArticleSources.ARTICLE_SOURCES;

    /**
     * The table <code>PUBLIC.ARTICLE_SUBSCRIPTIONS</code>.
     */
    public final ArticleSubscriptions ARTICLE_SUBSCRIPTIONS = ArticleSubscriptions.ARTICLE_SUBSCRIPTIONS;

    /**
     * The table <code>PUBLIC.ARTICLES</code>.
     */
    public final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>PUBLIC.EPISODES</code>.
     */
    public final Episodes EPISODES = Episodes.EPISODES;

    /**
     * The table <code>PUBLIC.EPISODES_ARTICLES</code>.
     */
    public final EpisodesArticles EPISODES_ARTICLES = EpisodesArticles.EPISODES_ARTICLES;

    /**
     * The table <code>PUBLIC.TELEGRAM_CHATS</code>.
     */
    public final TelegramChats TELEGRAM_CHATS = TelegramChats.TELEGRAM_CHATS;

    /**
     * The table <code>PUBLIC.TELEGRAM_UPDATES</code>.
     */
    public final TelegramUpdates TELEGRAM_UPDATES = TelegramUpdates.TELEGRAM_UPDATES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ArticleSources.ARTICLE_SOURCES,
            ArticleSubscriptions.ARTICLE_SUBSCRIPTIONS,
            Articles.ARTICLES,
            Episodes.EPISODES,
            EpisodesArticles.EPISODES_ARTICLES,
            TelegramChats.TELEGRAM_CHATS,
            TelegramUpdates.TELEGRAM_UPDATES
        );
    }
}
