/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq;


import dev.abarmin.bots.entity.jooq.tables.ArticleSources;
import dev.abarmin.bots.entity.jooq.tables.ArticleSubscriptions;
import dev.abarmin.bots.entity.jooq.tables.Articles;
import dev.abarmin.bots.entity.jooq.tables.Episodes;
import dev.abarmin.bots.entity.jooq.tables.EpisodesArticles;
import dev.abarmin.bots.entity.jooq.tables.TelegramChats;
import dev.abarmin.bots.entity.jooq.tables.TelegramUpdates;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ARTICLE_SOURCES</code>.
     */
    public static final ArticleSources ARTICLE_SOURCES = ArticleSources.ARTICLE_SOURCES;

    /**
     * The table <code>PUBLIC.ARTICLE_SUBSCRIPTIONS</code>.
     */
    public static final ArticleSubscriptions ARTICLE_SUBSCRIPTIONS = ArticleSubscriptions.ARTICLE_SUBSCRIPTIONS;

    /**
     * The table <code>PUBLIC.ARTICLES</code>.
     */
    public static final Articles ARTICLES = Articles.ARTICLES;

    /**
     * The table <code>PUBLIC.EPISODES</code>.
     */
    public static final Episodes EPISODES = Episodes.EPISODES;

    /**
     * The table <code>PUBLIC.EPISODES_ARTICLES</code>.
     */
    public static final EpisodesArticles EPISODES_ARTICLES = EpisodesArticles.EPISODES_ARTICLES;

    /**
     * The table <code>PUBLIC.TELEGRAM_CHATS</code>.
     */
    public static final TelegramChats TELEGRAM_CHATS = TelegramChats.TELEGRAM_CHATS;

    /**
     * The table <code>PUBLIC.TELEGRAM_UPDATES</code>.
     */
    public static final TelegramUpdates TELEGRAM_UPDATES = TelegramUpdates.TELEGRAM_UPDATES;
}
