spring:
  datasource:
    url: jdbc:h2:./database
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

telegram:
  bot:
    rss:
      digest:
        enabled: true
        botName: DigestBot
        botToken: ${DIGEST_BOT_TOKEN}
        webHookUrl: ${DIGEST_BOT_WEBHOOK}
        sqsQueue: ${DIGEST_BOT_SQS_QUEUE}
      reader:
        enabled: true
        scheduler:
          initialDelay: PT5S
          fixedDelay: PT1H
        sources:
          - sourceName: Inside Java
            sourceUrl: https://inside.java/feed.xml
          - sourceName: Vlad Mihalcea
            sourceUrl: https://vladmihalcea.com/feed/