spring:
  datasource:
    url: jdbc:h2:./database
    username: sa
    password: sa
  security:
    user:
      name: test
      password: test
telegram:
  bot:
    listener:
      webhook:
        enabled: false
      polling:
        enabled: false