spring:
  datasource:
    url: jdbc:h2:./database
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

telegram:
  bot:
    listener:
      webhook:
        enabled: true
      polling:
        enabled: false
    rss:
      digest:
        enabled: true
        botName: DigestBot
        botToken: ${DIGEST_BOT_TOKEN}
        webHook: ${DIGEST_BOT_WEBHOOK}
      reader:
        enabled: true
        scheduler:
          initialDelay: PT5S
          fixedDelay: PT1H