/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq.tables.records;


import dev.abarmin.bots.entity.jooq.tables.Articles;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticlesRecord extends UpdatableRecordImpl<ArticlesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ARTICLES.ARTICLE_ID</code>.
     */
    public void setArticleId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.ARTICLE_ID</code>.
     */
    public Integer getArticleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLES.ARTICLE_SOURCE_ID</code>.
     */
    public void setArticleSourceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.ARTICLE_SOURCE_ID</code>.
     */
    public Integer getArticleSourceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLES.ARTICLE_TITLE</code>.
     */
    public void setArticleTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.ARTICLE_TITLE</code>.
     */
    public String getArticleTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLES.ARTICLE_URL</code>.
     */
    public void setArticleUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.ARTICLE_URL</code>.
     */
    public String getArticleUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLES.ARTICLE_ADDED</code>.
     */
    public void setArticleAdded(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.ARTICLE_ADDED</code>.
     */
    public LocalDateTime getArticleAdded() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLES.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLES.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLES.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticlesRecord
     */
    public ArticlesRecord() {
        super(Articles.ARTICLES);
    }

    /**
     * Create a detached, initialised ArticlesRecord
     */
    public ArticlesRecord(Integer articleId, Integer articleSourceId, String articleTitle, String articleUrl, LocalDateTime articleAdded, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Articles.ARTICLES);

        setArticleId(articleId);
        setArticleSourceId(articleSourceId);
        setArticleTitle(articleTitle);
        setArticleUrl(articleUrl);
        setArticleAdded(articleAdded);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
