/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq.tables.records;


import dev.abarmin.bots.entity.jooq.tables.ArticleSources;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleSourcesRecord extends UpdatableRecordImpl<ArticleSourcesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_ID</code>.
     */
    public void setSourceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_ID</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_NAME</code>.
     */
    public void setSourceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_NAME</code>.
     */
    public String getSourceName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_URL</code>.
     */
    public void setSourceUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_URL</code>.
     */
    public String getSourceUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_LAST_UPDATED</code>.
     */
    public void setSourceLastUpdated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SOURCES.SOURCE_LAST_UPDATED</code>.
     */
    public LocalDateTime getSourceLastUpdated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SOURCES.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SOURCES.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SOURCES.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SOURCES.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleSourcesRecord
     */
    public ArticleSourcesRecord() {
        super(ArticleSources.ARTICLE_SOURCES);
    }

    /**
     * Create a detached, initialised ArticleSourcesRecord
     */
    public ArticleSourcesRecord(Integer sourceId, String sourceName, String sourceUrl, LocalDateTime sourceLastUpdated, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(ArticleSources.ARTICLE_SOURCES);

        setSourceId(sourceId);
        setSourceName(sourceName);
        setSourceUrl(sourceUrl);
        setSourceLastUpdated(sourceLastUpdated);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
