/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq.tables.records;


import dev.abarmin.bots.entity.jooq.tables.ArticleSubscriptions;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleSubscriptionsRecord extends UpdatableRecordImpl<ArticleSubscriptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.ARTICLE_SUBSCRIPTIONS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SUBSCRIPTIONS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SUBSCRIPTIONS.CHAT_ID</code>.
     */
    public void setChatId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SUBSCRIPTIONS.CHAT_ID</code>.
     */
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ARTICLE_SUBSCRIPTIONS.ARTICLE_SOURCE_ID</code>.
     */
    public void setArticleSourceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ARTICLE_SUBSCRIPTIONS.ARTICLE_SOURCE_ID</code>.
     */
    public Integer getArticleSourceId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleSubscriptionsRecord
     */
    public ArticleSubscriptionsRecord() {
        super(ArticleSubscriptions.ARTICLE_SUBSCRIPTIONS);
    }

    /**
     * Create a detached, initialised ArticleSubscriptionsRecord
     */
    public ArticleSubscriptionsRecord(Integer id, Long chatId, Integer articleSourceId) {
        super(ArticleSubscriptions.ARTICLE_SUBSCRIPTIONS);

        setId(id);
        setChatId(chatId);
        setArticleSourceId(articleSourceId);
        resetChangedOnNotNull();
    }
}
