/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq.tables.records;


import dev.abarmin.bots.entity.jooq.tables.EpisodesArticles;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EpisodesArticlesRecord extends UpdatableRecordImpl<EpisodesArticlesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.EPISODES_ARTICLES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EPISODES_ARTICLES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EPISODES_ARTICLES.EPISODE_ID</code>.
     */
    public void setEpisodeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EPISODES_ARTICLES.EPISODE_ID</code>.
     */
    public Integer getEpisodeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EPISODES_ARTICLES.ARTICLE_ID</code>.
     */
    public void setArticleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EPISODES_ARTICLES.ARTICLE_ID</code>.
     */
    public Integer getArticleId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EpisodesArticlesRecord
     */
    public EpisodesArticlesRecord() {
        super(EpisodesArticles.EPISODES_ARTICLES);
    }

    /**
     * Create a detached, initialised EpisodesArticlesRecord
     */
    public EpisodesArticlesRecord(Integer id, Integer episodeId, Integer articleId) {
        super(EpisodesArticles.EPISODES_ARTICLES);

        setId(id);
        setEpisodeId(episodeId);
        setArticleId(articleId);
        resetChangedOnNotNull();
    }
}
