/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq.tables.records;


import dev.abarmin.bots.entity.jooq.tables.TelegramUpdates;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TelegramUpdatesRecord extends UpdatableRecordImpl<TelegramUpdatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.TELEGRAM_UPDATES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TELEGRAM_UPDATES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TELEGRAM_UPDATES.UPDATE_ID</code>.
     */
    public void setUpdateId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TELEGRAM_UPDATES.UPDATE_ID</code>.
     */
    public Long getUpdateId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TELEGRAM_UPDATES.CHAT_ID</code>.
     */
    public void setChatId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TELEGRAM_UPDATES.CHAT_ID</code>.
     */
    public Long getChatId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TELEGRAM_UPDATES.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TELEGRAM_UPDATES.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>PUBLIC.TELEGRAM_UPDATES.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.TELEGRAM_UPDATES.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TelegramUpdatesRecord
     */
    public TelegramUpdatesRecord() {
        super(TelegramUpdates.TELEGRAM_UPDATES);
    }

    /**
     * Create a detached, initialised TelegramUpdatesRecord
     */
    public TelegramUpdatesRecord(Integer id, Long updateId, Long chatId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(TelegramUpdates.TELEGRAM_UPDATES);

        setId(id);
        setUpdateId(updateId);
        setChatId(chatId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
