/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.bots.entity.jooq.tables;


import dev.abarmin.bots.entity.jooq.Keys;
import dev.abarmin.bots.entity.jooq.Public;
import dev.abarmin.bots.entity.jooq.tables.TelegramChats.TelegramChatsPath;
import dev.abarmin.bots.entity.jooq.tables.records.TelegramUpdatesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TelegramUpdates extends TableImpl<TelegramUpdatesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.TELEGRAM_UPDATES</code>
     */
    public static final TelegramUpdates TELEGRAM_UPDATES = new TelegramUpdates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TelegramUpdatesRecord> getRecordType() {
        return TelegramUpdatesRecord.class;
    }

    /**
     * The column <code>PUBLIC.TELEGRAM_UPDATES.ID</code>.
     */
    public final TableField<TelegramUpdatesRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.TELEGRAM_UPDATES.UPDATE_ID</code>.
     */
    public final TableField<TelegramUpdatesRecord, Long> UPDATE_ID = createField(DSL.name("UPDATE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TELEGRAM_UPDATES.CHAT_ID</code>.
     */
    public final TableField<TelegramUpdatesRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.TELEGRAM_UPDATES.CREATED_AT</code>.
     */
    public final TableField<TelegramUpdatesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>PUBLIC.TELEGRAM_UPDATES.UPDATED_AT</code>.
     */
    public final TableField<TelegramUpdatesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private TelegramUpdates(Name alias, Table<TelegramUpdatesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TelegramUpdates(Name alias, Table<TelegramUpdatesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.TELEGRAM_UPDATES</code> table reference
     */
    public TelegramUpdates(String alias) {
        this(DSL.name(alias), TELEGRAM_UPDATES);
    }

    /**
     * Create an aliased <code>PUBLIC.TELEGRAM_UPDATES</code> table reference
     */
    public TelegramUpdates(Name alias) {
        this(alias, TELEGRAM_UPDATES);
    }

    /**
     * Create a <code>PUBLIC.TELEGRAM_UPDATES</code> table reference
     */
    public TelegramUpdates() {
        this(DSL.name("TELEGRAM_UPDATES"), null);
    }

    public <O extends Record> TelegramUpdates(Table<O> path, ForeignKey<O, TelegramUpdatesRecord> childPath, InverseForeignKey<O, TelegramUpdatesRecord> parentPath) {
        super(path, childPath, parentPath, TELEGRAM_UPDATES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TelegramUpdatesPath extends TelegramUpdates implements Path<TelegramUpdatesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TelegramUpdatesPath(Table<O> path, ForeignKey<O, TelegramUpdatesRecord> childPath, InverseForeignKey<O, TelegramUpdatesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TelegramUpdatesPath(Name alias, Table<TelegramUpdatesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TelegramUpdatesPath as(String alias) {
            return new TelegramUpdatesPath(DSL.name(alias), this);
        }

        @Override
        public TelegramUpdatesPath as(Name alias) {
            return new TelegramUpdatesPath(alias, this);
        }

        @Override
        public TelegramUpdatesPath as(Table<?> alias) {
            return new TelegramUpdatesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TelegramUpdatesRecord, Integer> getIdentity() {
        return (Identity<TelegramUpdatesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TelegramUpdatesRecord> getPrimaryKey() {
        return Keys.TELEGRAM_UPDATES_PK;
    }

    @Override
    public List<UniqueKey<TelegramUpdatesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UPDATE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<TelegramUpdatesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.UPDATE_CHAT_ID_FK);
    }

    private transient TelegramChatsPath _telegramChats;

    /**
     * Get the implicit join path to the <code>PUBLIC.TELEGRAM_CHATS</code>
     * table.
     */
    public TelegramChatsPath telegramChats() {
        if (_telegramChats == null)
            _telegramChats = new TelegramChatsPath(this, Keys.UPDATE_CHAT_ID_FK, null);

        return _telegramChats;
    }

    @Override
    public TelegramUpdates as(String alias) {
        return new TelegramUpdates(DSL.name(alias), this);
    }

    @Override
    public TelegramUpdates as(Name alias) {
        return new TelegramUpdates(alias, this);
    }

    @Override
    public TelegramUpdates as(Table<?> alias) {
        return new TelegramUpdates(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TelegramUpdates rename(String name) {
        return new TelegramUpdates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TelegramUpdates rename(Name name) {
        return new TelegramUpdates(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TelegramUpdates rename(Table<?> name) {
        return new TelegramUpdates(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TelegramUpdates where(Condition condition) {
        return new TelegramUpdates(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TelegramUpdates where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TelegramUpdates where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TelegramUpdates where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TelegramUpdates where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TelegramUpdates where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TelegramUpdates where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TelegramUpdates where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TelegramUpdates whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TelegramUpdates whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
