name: Deploy to Digital Ocean

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version to deploy'
        required: true
        default: '0.0.x'
      BRANCH:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.BRANCH }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          gradle-version: wrapper
          arguments: build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./build/libs/app.jar

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Production
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: .
      - name: Upload to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./app.jar"
          target: /opt/app/${{ github.event.inputs.VERSION }}
      - name: Stop existing app
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            APP_PID=$(/home/${{ secrets.SERVER_USERNAME }}/.sdkman/candidates/java/21.0.1-amzn/bin/jps | grep app.jar | grep -Eo '[0-9]+')
            kill $APP_PID
      - name: Start new app
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /opt/app/
            rm app.jar
            ln -fs /opt/app/${{ github.event.inputs.VERSION }}/app.jar app.jar
            ./run.sh
      - name: Update build information
        run: |
          echo "Deployed version is ${{ github.event.inputs.VERSION }}" >> $GITHUB_STEP_SUMMARY